seed: 1234
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "./dhs_output/ckpt/icassp_2024"
  log_path: "./output/log/icassp_2024"
  result_path: "./output/result/icassp_2024"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000001, 1100000, 1300000, 1400000]
  anneal_rate: 0.3
step:
  total_step: 1500000
  log_step: 100
  synth_step: 200
  val_step: 200
  save_step: 100
