seed: 1234
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "/mnt/hdd/ICASSP2024_FS2-develop/ICASSP2024_FS2-develop/output/ckpt/inter_2026"
  log_path: "/mnt/hdd/ICASSP2024_FS2-develop/ICASSP2024_FS2-develop/output/log/inter_2026"
  result_path: "/mnt/hdd/ICASSP2024_FS2-develop/ICASSP2024_FS2-develop/output/result/inter_2026"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000001, 1100000, 1300000, 1400000]
  anneal_rate: 0.3
step:
  total_step: 1500000
  log_step: 1000
  synth_step: 2000
  val_step: 1000
  save_step: 10000
  extractor_only_step: 300000
